export { default as Home } from './home/Home';
export { default as Services } from './services/Services';
export { default as Work } from './work/Work';
export { default as Blog } from './blog/Blog';
export { default as Career } from './career/Career';
export { default as About } from './about/About';
export { default as Header } from './common/navbar/Header';
export { default as Faq } from './common/faq/faq';
export { default as Footer } from './common/Footer/Footer';
export { default as MenuItem } from './common/Footer/FooterItems';
export { default as QuoteSection } from './common/quote-section/quotes';
export { BrowserRouter as Router, Route, Routes, useLocation } from 'react-router-dom';